test

diff --git a/.github/workflows/api-cicd.yml b/.github/workflows/api-cicd.yml
--- a/.github/workflows/api-cicd.yml
+++ b/.github/workflows/api-cicd.yml
@@ -24,6 +24,15 @@ jobs:
           aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
           aws-region: eu-north-1 
 
+      - name: Debug Secret Connection
+        run: |
+          if [ -z "${{ secrets.AWS_ACCESS_KEY_ID }}" ]; then
+            echo "❌ GitHub cannot see the Access Key!"
+            exit 1
+          else
+            echo "✅ GitHub sees the Access Key!"
+          fi
+
       - name: Install Ansible on GitHub Runner
         run: |
           sudo apt-get update
